version: 2.1
orbs:
  node: circleci/node@4.1.0
jobs:
  install-package:
    executor: node/default
    steps:
      - checkout
      - node/install-packages:
          app-dir: ./firebase/functions
workflows:
  node-tests:
    jobs:
      - install-package  
      - node/test:
         app-dir: ./firebase/functions
