version: 2.1
orbs:
  node: circleci/node@4.1.0
workflows:
  node-tests:
    jobs:
      - node/install:
         app-dir: ./firebase/functions       
      - node/test:
         app-dir: ./firebase/functions
