version: 2.1
orbs:
  node: circleci/node@4.1.0
jobs:
  functions-deploy:
    executor: node/default
    working_directory: ~/project/firebase
    steps:
      - checkout
      - run: ls
      - node/install-packages:
          app-dir: ~/project/firebase/functions
      - run: npm init -y 
      - run: npm install --save-dev firebase-tools
      - run: ./node_modules/.bin/firebase deploy --token=$FIREBASE_TOKEN
workflows:
  deploy:
    jobs:
      - node/test:
         app-dir: ./firebase/functions
      - functions-deploy:
          requires:
            - node/test
